

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Welcome to the casestudy</h3>
            </div>
            <div class="panel-body">
                <p>
                    This is a simple webpage which displays the characterstics of the Certificates.
                    <br><a href="/certificate">Please click here to get the list of available certificates.</a>,
                </p>
            </div>
        </div>
    </div>
</div>
